# Generated by Django 4.0.4 on 2022-05-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_sale_product_status_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
