# Generated by Django 4.0.4 on 2022-05-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
